// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/[...]').default>>>>
    }
    '/api/auth/hello': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/hello').default>>>>
    }
    '/api/forms/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/forms/[id].get').default>>>>
    }
    '/api/forms/:id/responses': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/forms/[id]/responses.get').default>>>>
    }
    '/api/forms/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/forms/create.post').default>>>>
    }
    '/api/forms/my': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/forms/my.get').default>>>>
    }
    '/api/forms/publish': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/forms/publish.post').default>>>>
    }
    '/api/forms/share/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/forms/share/[id].get').default>>>>
    }
    '/api/hello': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hello').default>>>>
    }
    '/api/responses': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/responses.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+nitro-server@4.4.4_@b_0fe8aedda45cfaf94561f0f2fb12a017/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+icon@2.2.2_magicast@0_46b4fd923537fb5a8a193e05d0555ac5/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
  }
}
export {}